### PR TITLE
Changes in section on localization of (pre-triangulated) categories

### PR DESCRIPTION
**Pull request by eliasgv3**
Inside each commit there is a summary with the changes.

### CODE REVIEW

**Comment by eliasgv3** [comment]
Thank you for the reading through the edit. I will answer from your last thought to the first one.

You're right that I didn't give the complete argument in lemma-iterated-category-localization; it is not that immediate. Here is the full proof that $Q(T)$ is a LMS:

    If $T$ is a left multiplicative system,
	then the set $Q(T)$ satisfies LMS1 for
	$Q$ is bijective on objects and preserves identities.
	We see it satisfies LMS2.
	Given morphisms $Q(t):Q(X)\to Q(Z)$ and $s^{-1}g:Q(X)\to Q(Y)$,
	where $t\in T$ and $s:Y'\to Y$ is in $S$,
	there are dotted morphisms that make the following diagram commute:
	\[
	\xymatrix{
		Q(X) \ar@{->}[r]^{Q(g)} \ar@{->}[d]_{Q(t)} & Q(Y') \ar@{.>}[d]^{Q(t')} & Q(Y) \ar@{->}[l]_{Q(s)} \\
		Q(Z) \ar@{.>}[r]^{Q(f)} & Q(W) & 
	}
	\]
	where $t'\in T$. Hence, defining $t''=t'\circ s\in T$,
	we have that $Q(t'')\circ s^{-1}g=Q(t')\circ Q(g)=Q(f)\circ Q(t)$,
	which proves LMS2. Lastly, to see LMS3, suppose we have $a,b:Q(X)\to Q(Y)$
	and a morphism $t\in T$ with target $X$ such that
	$a\circ Q(t)=b\circ Q(t)$. By Lemma \ref{lemma-morphisms-left-localization}, we may assume $a=s^{-1}f$,
	$b=s^{-1}g$, for some $s:Y'\to Y$ in $S$. Hence, we have
	$Q(s)^{-1}\circ Q(f)\circ Q(t)
	=Q(s)^{-1}\circ Q(g)\circ Q(t)$, i.e.,
	$Q(f\circ t)= Q(g\circ t)$.
	By Lemma \ref{lemma-equality-morphisms-left-localization},
	this means that there is $s\in S$ with source $Y$ such that
	$s\circ f\circ t=s\circ f\circ t$.
	By LMS3 for $T$, we get a $t'\in T$ postcomposable with $s$ such that
	$t'\circ s\circ f=t'\circ s\circ g$.
	In particular, $t'\circ s\in T$,
	and after passing the last equality through $Q$, we are done.

Regarding the uniqueness in the statement of [05R6](https://stacks.math.columbia.edu/tag/05R6): I think what you propose is fine. The argument is already written in the proof of the new result lemma-localization-unique-pre-triangulated-structure I added. (If you consider it necessary, I guess it's okay to delete the new statement and include the content of its proof inside [05R6](https://stacks.math.columbia.edu/tag/05R6), or whatever.)

Regarding the definition of pre-triangulated category of the SP: I don't think my opinion about this may be valuable. I am a student that is familiarizing himself for the first time with the theory of triangulated categories (my main reason to learn it is to derive functors in algebraic geometry). I guess asking $[1]$ to be an isomorphism may be psychologically better at the beginning, but all the literature on triangulated categories seems to require the translation functor only to be an auto-equivalence. Probably for the equivalence invariance that Christian commented on.

**Comment by aisejohan** [comment]
OK, this is I think proving it for both S and T being left multiplicative systems. But I am *not* *at* *all* suggesting you write it out in the other case. I just want to point out that it is a bit annoying. Because we do not need this material right now (as we can fix the objections in the comments in another way), I might not incorporate it until we _do_ need it. Hope that makes sense.

**Comment by eliasgv3** [comment]
Okay, yeah. I guess it may not be that easy to prove it when $S$ and $T$ are of opposite handedness. I actually didn't need lemma-iterated-category-localization in full generality. I just needed it to prove the new equality equation-localization-morphisms-iterated-colimit that I added. By lemma-multiplicative-system, it suffices to prove the weaker version of lemma-iterated-category-localization for $S$ and $T$ of same handedness. The proof for this is then already written.

**Comment by eliasgv3** [comment]
@aisejohan Hey, I just changed the name of the branch and as an unintended side effect this pull request was closed. I changed it back to the original name, sorry for the inconvenience.

**Comment by aisejohan** [comment]
Closed by commit 593c7279d44c44700b1b22fe74a71e2dabb7f001

**Pull request closed without merging**
