### PR TITLE
minor bugs (in particular, missing definitions) mostly in homology.tex, take 2

### PR DESCRIPTION
**Pull request by darijgr**
This is https://github.com/stacks/stacks-project/pull/36 with your changes worked in, with two exceptions:

- I don't feel like I could formulate the skyscraper replacement well, sorry.

- My proof of lemma-characterize-injective is not a one-step argument; I would not summarize it as "follows directly from Lemma \ref{lemma-kernel-mono}" or in any other similarly short way. Am I overcomplicating it?

### CODE REVIEW

**Comment by aisejohan** [comment]
OK, I applied the changes by hand. Thanks!

After this I removed the definition of the skyscraper complexes and I clearly stated that we always think of an additive category as sitting inside the category of complexes in degree 0. I also explained that we sometimes use the notation A and sometimes the notation A[0] for the complex zero except having A in degree 0. This actually comes up a fair bit in practice and everybody always uses this abuse of notation.

**Comment by darijgr** [comment]
Sorry for the low signal-to-noise on this branch -- I should have started
reading up on the conventions before writing away. Thanks for getting them
in!

I'd like to defend my change of x -> y to y -> z in Lemma
\ref{lemma-preadditive-zero}, though. The problem with the letter x is that
it stands for the zero object in the first part of the lemma. Even if you
call it "an object $0$", it's probably better to not clobber the letter x
more often the necessary.

Also: "Recall that $\Ker(f)$ of $f$": remove "of $f$" or add "the kernel".

On Fri, Jul 7, 2017 at 1:45 AM, Aise Johan de Jong <notifications@github.com

**Comment by aisejohan** [comment]
Thanks for the typo!

**Comment by darijgr** [comment]
By the way, nice argument on the mono<==>injective lemma! I guess I
overthought it.

On Fri, Jul 7, 2017 at 2:05 AM, Aise Johan de Jong <notifications@github.com

**Pull request closed without merging**
