### PR TITLE
Upgrade links to https where possible

### PR DESCRIPTION
**Pull request by iblech**
In the process I repaired two or three links which fell prey to bitrot.

(This pull request wasn't created using blind search/replace. I used a [script](https://github.com/luga-ev/website/blob/master/rewrite-http-to-https.pl) to upgrade only those http urls for which the corresponding https url works.)

### CODE REVIEW

**Comment by aisejohan** [comment]
Dear Ingo, can you assure me the new links work? Did you test them? It looks good, but I just want to make sure. Best, Johan

**Comment by iblech** [comment]
I trust my script, which ensures that no new 404's arise. :-)

However, I just additionally checked the links manually, found four broken links (which were also broken before the change), and fixed them in the second commit.

**Comment by aisejohan** [comment]
Hi, OK, I actually applied the previous thing already, but now I have also applied the last edit by hand (forgot to make you author of this last patch -- apologies). Hope it is OK now. Before you send more patches please sync with master.

**Comment by iblech** [comment]
No worries, and yes, everything looks fine! I don't have more patches in the pipeline right now, but of course will properly sync for the next patch.

**Pull request closed without merging**
