### PR TITLE
More detailed proofs in derived categories

### PR DESCRIPTION
**Pull request by eliasgv3**
I added more details to already existing proofs (changes are explained in each commit). If you think I am being "too detailed" in some excerpt from what I wrote, I guess it's okay to ignore it by not adding it.

### CODE REVIEW

**Comment by aisejohan** [comment]
Just want to make sure that you know I will not automatically accept these proposed changes. So please make sure you do not put too much time and effort into this until I get back to you. For example, in the case of your pull request #165 I will probably not add most of what you wrote and make small changes that fix the actual problems you pointed out.

I will definitively look at what you wrote and comment on it when I next go through all the comments!

**Comment by eliasgv3** [comment]
No problem, thank you for letting me know. I do all of these pull requests partially to explain it to myself, partially to see I didn't get it wrong and partially to improve the text for everyone to read. If anything I ever propose is not deemed worth to be added, it's fair. I think sometimes I just don't fully understand the scope of text, and this is because I am writing all of this while learning the material for the first time. Any kind of feedback helps me finding out more about the scope.

**Comment by aisejohan** [comment]
OK, I am going to close pull requests 166, 167, and 168 without explanation. However, I would like to discuss offline with you; if you are interested please email me. My email address can be found on the math department website of Columbia University.

**Comment by eliasgv3** [comment]
@aisejohan Okay, no problem. I could not find your email address in [http://math.columbia.edu/~dejong/](http://math.columbia.edu/~dejong/) so I emailed you to the email address which appears in [https://github.com/aisejohan](https://github.com/aisejohan). I don't know if that is the correct email address.

**Pull request closed without merging**
