### PR TITLE
minor bugs (in particular, missing definitions) mostly in homology.tex

### PR DESCRIPTION
**Pull request by darijgr**
See the respective commit messages for details.

### CODE REVIEW

**Comment by darijgr** [comment]
Sorry, but I think some information got lost here. Which change should no longer be necessary? What lemma has become less clear? What proof is too detailed? You might have made comments to specific lines of my commits, but all I see are the comments, not the lines they belong to :(

Can you fix the skyscraper part? I think this abuse of notation should be defined *somewhere*, and I am not particularly happy with how I did it myself; I just don't see how to do it shorter.

**Comment by aisejohan** [comment]
Oops, when I left my comments I wrote each comment when reviewing one of the commits but in this interface it does not show which commit I was commenting on. Argh!

I am going to close this pull request now. Then please make another pull request with the changes taking into account what you understood of my comments. Then I will go over them again and comment on the actual commits directly so you can see what I mean.

Sorry for all the confusion!!!

**Comment by darijgr** [comment]
TBH all I've understood of your commits is the LaTeX style issues, which I've fixed in this PR. Sorry, but I'll need more help, particularly as far as what should be left out of the proofs.

**Comment by aisejohan** [comment]
OK, here is what you should do at least and then split do another pull request:
-- undo change to statement lemma-preadditive-zero: IHMO I think the statement of the lemma has become less clear with the changes you made
-- remove the proof of lemma-preadditive-zero: the level of the readers of the Stacks project should be so that they can prove this lemma. If we add a proof for this lemma it should maybe just be a couple of sentences pointing out any perceived tricky part.
-- add \medskip\noindent in proof lemma-additive-additive
-- remove comments in definition-kernel: if you think it is necessary to explain the meaning of kernel and cokernel, then please do not do this inside the definition itself but do it directly following the definition
-- lemma-kernel-mono: this lemma could be useful to some of our readers (but only those that haven't had any course on abstract algebra I would think). So adding the lemma is fine. But please just replace the proof by something like: ``The kernel is a monomorphism by the uniqueness required in the definition of a kernel.''
-- proof of lemma-abelian-opposite: this is OK
-- proof of lemma-characterize-injective: if we add lemma-kernel-mono, then this can be dispensed with by a reference to that lemma. Otherwise, again I suggest just briefly saying why it is true.
-- remove skyscraper stuff and add discussion of abuse of language we mentioned above.

**Comment by darijgr** [comment]
Thanks -- see https://github.com/stacks/stacks-project/pull/37 .

**Pull request closed without merging**
